In [98]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [99]:
df = pd.read_csv("E:\\Feature engineering\\Datasets\\titanic.csv")

In [100]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [101]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [102]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [103]:
df = df.drop(['PassengerId','Name'],axis = 1)

In [104]:
df_c = df.select_dtypes(include = 'object')

In [105]:
df_c = df_c.drop(['Ticket'],axis = 1)

In [106]:
df_c.head()

Sex Cabin Embarked
0    male   NaN        Q
1  female   NaN        S
2    male   NaN        Q
3    male   NaN        S
4  female   NaN        S

In [107]:
print("Number of unique labels in Sex column = {} ".format(len(df_c.Sex.unique())))
print()
print("Number of unique labels in Cabin column = {} ".format(len(df_c.Cabin.unique())))
print()
print("Number of unique labels in Embarked column = {} ".format(len(df_c.Embarked.unique())))

Number of unique labels in Sex column = 2 

Number of unique labels in Cabin column = 77 

Number of unique labels in Embarked column = 3 


In [108]:
df_c.isnull().sum()

Sex           0
Cabin       327
Embarked      0
dtype: int64

### Converting Cabin feature data into single label and checking cardinality 

In [109]:
df_c['Cabin_single'] = df_c['Cabin'].astype(str).str[0]


In [110]:
df_c.columns

Index(['Sex', 'Cabin', 'Embarked', 'Cabin_single'], dtype='object')

In [111]:
df_c.head()

Sex Cabin Embarked Cabin_single
0    male   NaN        Q            n
1  female   NaN        S            n
2    male   NaN        Q            n
3    male   NaN        S            n
4  female   NaN        S            n

In [112]:
len(df_c.Cabin.unique())

77

In [113]:
df_c.Cabin_single.unique()

array(['n', 'B', 'E', 'A', 'C', 'D', 'F', 'G'], dtype=object)

In [114]:
len(df_c.Cabin_single.unique())

8

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
X_train,X_test,y_train , y_test = train_test_split(df_c , df['Survived'] , test_size=0.22 , random_state=42)

In [117]:
X_train.head()

Sex Cabin Embarked Cabin_single
327    male   NaN        C            n
5      male   NaN        S            n
45     male   NaN        S            n
140  female   NaN        S            n
145    male   NaN        S            n

In [118]:
X_test.head()

Sex  Cabin Embarked Cabin_single
321    male  F E57        C            F
324  female    NaN        S            n
388    male    NaN        Q            n
56     male    NaN        S            n
153  female    NaN        S            n

In [119]:
y_train.head()

327    0
5      0
45     0
140    1
145    0
Name: Survived, dtype: int64

In [120]:
y_test.head()

321    0
324    1
388    0
56     0
153    1
Name: Survived, dtype: int64

### checking whether labels in Sex column were equally divide or not 

In [121]:
train_sex = [i for i in X_train['Sex'].unique() if i not in X_test['Sex'].unique()]
print(len(train_sex))

0


In [122]:
test_sex = [i for i in X_test['Sex'].unique() if i not in X_train['Sex'].unique()]
print(len(test_sex))

0


### checking whether labels in Embarked column were equally divide or not

In [123]:
train_embarked = [i for i in X_train['Embarked'].unique() if i not in X_test['Embarked'].unique()]
print(len(train_embarked))

0


In [124]:
test_embarked = [i for i in X_test['Embarked'].unique() if i not in X_train['Embarked'].unique()]
print(len(test_embarked))

0


### checking whether labels in Embarked column were equally divide or not

In [125]:
train_Cabin = [i for i in X_train['Cabin'].unique() if i not in X_test['Cabin'].unique()]
print(len(train_Cabin))

58


- there are 58 lables which are in train data part and not in test data part 

In [126]:
test_Cabin = [i for i in X_test['Cabin'].unique() if i not in X_train['Cabin'].unique()]
print(len(test_Cabin))

17


- They are 17 lables which are in test data and not in training data , This huge cadinality definatelly harm our model so , we can select only staring part of the label .

### checking whether cabin single selected column divide perfectly or not for train and test part 

In [127]:
train_Cabin_single = [i for i in X_train['Cabin_single'].unique() if i not in X_test['Cabin_single'].unique()]
print(len(train_Cabin_single))
print(train_Cabin_single)

1
['G']


In [128]:
X_train['Cabin_single'].unique()

array(['n', 'E', 'B', 'C', 'F', 'A', 'D', 'G'], dtype=object)

In [129]:
test_Cabin_single = [i for i in X_test['Cabin_single'].unique() if i not in X_train['Cabin_single'].unique()]
print(len(test_Cabin_single))

0


In [130]:
X_test['Cabin_single'].unique()

array(['F', 'n', 'D', 'C', 'E', 'A', 'B'], dtype=object)

- By collecting only starting letter will reduce the cardinality in the data , because we can reduce number of labels in the data

###  Allocating the numbers for cabin column without single character selecting and with single character selecting 

In [131]:
cabin_values = {j:i for i , j in enumerate(df_c['Cabin'].unique() , 0)}
cabin_values

{nan: 0,
 'B45': 1,
 'E31': 2,
 'B57 B59 B63 B66': 3,
 'B36': 4,
 'A21': 5,
 'C78': 6,
 'D34': 7,
 'D19': 8,
 'A9': 9,
 'D15': 10,
 'C31': 11,
 'C23 C25 C27': 12,
 'F G63': 13,
 'B61': 14,
 'C53': 15,
 'D43': 16,
 'C130': 17,
 'C132': 18,
 'C101': 19,
 'C55 C57': 20,
 'B71': 21,
 'C46': 22,
 'C116': 23,
 'F': 24,
 'A29': 25,
 'G6': 26,
 'C6': 27,
 'C28': 28,
 'C51': 29,
 'E46': 30,
 'C54': 31,
 'C97': 32,
 'D22': 33,
 'B10': 34,
 'F4': 35,
 'E45': 36,
 'E52': 37,
 'D30': 38,
 'B58 B60': 39,
 'E34': 40,
 'C62 C64': 41,
 'A11': 42,
 'B11': 43,
 'C80': 44,
 'F33': 45,
 'C85': 46,
 'D37': 47,
 'C86': 48,
 'D21': 49,
 'C89': 50,
 'F E46': 51,
 'A34': 52,
 'D': 53,
 'B26': 54,
 'C22 C26': 55,
 'B69': 56,
 'C32': 57,
 'B78': 58,
 'F E57': 59,
 'F2': 60,
 'A18': 61,
 'C106': 62,
 'B51 B53 B55': 63,
 'D10 D12': 64,
 'E60': 65,
 'E50': 66,
 'E39 E41': 67,
 'B52 B54 B56': 68,
 'C39': 69,
 'B24': 70,
 'D28': 71,
 'B41': 72,
 'C7': 73,
 'D40': 74,
 'D38': 75,
 'C105': 76}

In [132]:
df_c.columns

Index(['Sex', 'Cabin', 'Embarked', 'Cabin_single'], dtype='object')

In [133]:
import warnings
warnings.filterwarnings("ignore")

In [135]:
X_train.loc[: , 'cabin_normal_values'] = X_train.loc[: , 'Cabin'].map(cabin_values)
X_test.loc[: , 'cabin_normal_values'] = X_test.loc[: , 'Cabin'].map(cabin_values)


In [137]:
X_test.columns

Index(['Sex', 'Cabin', 'Embarked', 'Cabin_single', 'cabin_normal_values'], dtype='object')

In [138]:
X_train.isnull().sum()

Sex                      0
Cabin                  254
Embarked                 0
Cabin_single             0
cabin_normal_values      0
dtype: int64

In [140]:
X_test.isnull().sum()

Sex                     0
Cabin                  73
Embarked                0
Cabin_single            0
cabin_normal_values     0
dtype: int64

### Allocating values for cabin single character column

In [141]:
cabin_single_values = {j:i for i , j in enumerate(df_c['Cabin_single'].unique())}

In [142]:
cabin_single_values

{'n': 0, 'B': 1, 'E': 2, 'A': 3, 'C': 4, 'D': 5, 'F': 6, 'G': 7}

In [143]:
X_train.loc[: , 'Cabin_single_values'] = X_train.loc[: , 'Cabin_single'].map(cabin_single_values)
X_test.loc[: , 'Cabin_single_values'] = X_test.loc[: , 'Cabin_single'].map(cabin_single_values)

In [144]:
X_train.columns

Index(['Sex', 'Cabin', 'Embarked', 'Cabin_single', 'cabin_normal_values',
       'Cabin_single_values'],
      dtype='object')

In [146]:
X_train.tail()

Sex Cabin Embarked Cabin_single  cabin_normal_values  \
71   male   NaN        S            n                    0   
106  male   NaN        Q            n                    0   
270  male    C6        C            C                   27   
348  male   NaN        S            n                    0   
102  male   NaN        Q            n                    0   

     Cabin_single_values  
71                     0  
106                    0  
270                    4  
348                    0  
102                    0

In [147]:
X_train['Sex'] = X_train['Sex'].map({"male":0 , "female":1}).astype(int)
X_test['Sex'] = X_test['Sex'].map({"male":0 , "female":1}).astype(int)



In [148]:
X_train.Embarked.unique()

array(['C', 'S', 'Q'], dtype=object)

In [149]:
X_train['Embarked'] = X_train['Embarked'].map({"C":0 , "S":1 , "Q":2}).astype(int)
X_test['Embarked'] = X_test['Embarked'].map({"C":0 , "S":1 , "Q":2}).astype(int)






In [150]:
X_train.head()

Sex Cabin  Embarked Cabin_single  cabin_normal_values  \
327    0   NaN         0            n                    0   
5      0   NaN         1            n                    0   
45     0   NaN         1            n                    0   
140    1   NaN         1            n                    0   
145    0   NaN         1            n                    0   

     Cabin_single_values  
327                    0  
5                      0  
45                     0  
140                    0  
145                    0

In [151]:
X_train.isnull().sum()

Sex                      0
Cabin                  254
Embarked                 0
Cabin_single             0
cabin_normal_values      0
Cabin_single_values      0
dtype: int64

In [152]:
y_train.head()

327    0
5      0
45     0
140    1
145    0
Name: Survived, dtype: int64

In [159]:
from sklearn.ensemble import RandomForestClassifier

In [160]:
reg = RandomForestClassifier(n_estimators=200, random_state=39)

In [161]:
reg.fit(X_train[["Sex","Embarked","cabin_normal_values"]] , y_train)

RandomForestClassifier(n_estimators=200, random_state=39)

In [162]:
reg.score(X_train[["Sex","Embarked","cabin_normal_values"]] , y_train)

1.0

- Running the instance makes the probability predictions and then prints the input data instance and the probability of each instance belonging to the first and second classes (0 and 1).

In [163]:
y_train_pred = reg.predict_proba(X_train[["Sex","Embarked","cabin_normal_values"]])


In [165]:
y_train_pred[:10]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [166]:
y_test_pred = reg.predict_proba(X_test[["Sex","Embarked","cabin_normal_values"]])

In [167]:
y_test_pred[:10]

array([[0.945, 0.055],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ]])

In [168]:
from sklearn.metrics import roc_auc_score

In [171]:
print("train set  = {} ".format(roc_auc_score(y_train , y_train_pred[: , 1])))
print("test set  = {} ".format(roc_auc_score(y_test , y_test_pred[: , 1])))



train set  = 1.0 
test set  = 1.0 


## cabin single values 

In [180]:
reg = RandomForestClassifier(n_estimators=200, random_state=39)

In [181]:
reg.fit(X_train[["Sex","Embarked","Cabin_single_values"]] , y_train)

RandomForestClassifier(n_estimators=200, random_state=39)

In [182]:
reg.score(X_train[["Sex","Embarked","Cabin_single_values"]] , y_train)

1.0

- Running the instance makes the probability predictions and then prints the input data instance and the probability of each instance belonging to the first and second classes (0 and 1).

In [183]:
y_train_pred = reg.predict_proba(X_train[["Sex","Embarked","Cabin_single_values"]])


In [184]:
y_train_pred[:10]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [185]:
y_test_pred = reg.predict_proba(X_test[["Sex","Embarked","Cabin_single_values"]])

In [186]:
y_test_pred[:10]

array([[0.985, 0.015],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ]])

In [187]:
from sklearn.metrics import roc_auc_score

In [188]:
print("train set  = {} ".format(roc_auc_score(y_train , y_train_pred[: , 1])))
print("test set  = {} ".format(roc_auc_score(y_test , y_test_pred[: , 1])))



train set  = 1.0 
test set  = 1.0 


In [172]:
from sklearn.linear_model import LogisticRegression

In [173]:
reg = LogisticRegression()

In [176]:
reg.fit(X_train[["Sex","Embarked","Cabin_single_values"]] , y_train)

LogisticRegression()

In [177]:
y_train_pred = reg.predict_proba(X_train[["Sex","Embarked","Cabin_single_values"]])
y_test_pred = reg.predict_proba(X_test[["Sex","Embarked","Cabin_single_values"]])

In [178]:
y_test_pred[:10]

array([[0.9491774 , 0.0508226 ],
       [0.05875315, 0.94124685],
       [0.96723047, 0.03276953],
       [0.97140692, 0.02859308],
       [0.05875315, 0.94124685],
       [0.97140692, 0.02859308],
       [0.05875315, 0.94124685],
       [0.97140692, 0.02859308],
       [0.05875315, 0.94124685],
       [0.97140692, 0.02859308]])

In [179]:
print("train set logistic  = {} ".format(roc_auc_score(y_train , y_train_pred[: , 1])))
print("test set logistic   = {} ".format(roc_auc_score(y_test , y_test_pred[: , 1])))



train set logistic  = 1.0 
test set logistic   = 0.9999999999999999 
